apiVersion: apps/v1beta1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: hello-deployment
  labels:
    app: hello-app
spec:
  selector:
    matchLabels:
      app: hello-app
  replicas: 2
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
        - name: hello-app
          image: k8sexample/hello-service
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
              name: server
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 20
            timeoutSeconds: 10
            periodSeconds: 20
            failureThreshold: 1
          env:
            - name: HELLO_SERVICE_GREETER
              valueFrom:
                configMapKeyRef:
                  name: hello-kubernetes-configmap
                  key: hello-service-greeter
            - name: PERSON_NAMES_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: hello-kubernetes-configmap
                  key: person-names-service-url
